logging:
  level:
    com.netflix.eureka: 'off'
    com.netflix.discovery: 'off'

spring:
  profiles:
    # Comma-separated list of active profiles
    active: default
  jpa:
    database: h2
    generate-ddl: true
  sleuth:
    sampler:
      percentage: 1.0
    log:
      json:
        enabled: true

server:
  # Server HTTP port
  port: ${PORT:0}

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    hostname: ${vcap.application.uris[0]:119.207.76.90}
#    nonSecurePort: 80
    prefer-ip-address: true
    metadataMap:
#      instanceId: ${vcap.application.instance_id:${server.port}:${spring.application.name}}:${spring.application.instance_id}
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    leaseRenewalIntervalInSeconds: 3
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
      defauktZone: ${vcap.services.discovery-service.credentials.uri:119.207.76.90:8761/eureka/
