logging:
  level:
    com.netflix.eureka: 'off'
    com.netflix.discovery: 'off'

spring:
  profiles:
    # Comma-separated list of active profiles
    active: default
  jpa:
    database: h2
    generate-ddl: true

server:
  # Server HTTP port
  port: ${PORT:0}

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    hostname: ${vcap.application.uris[0]:119.207.76.90}
#    nonSecurePort: 80
    prefer-ip-address: true
    metadataMap:
#      instanceId: ${vcap.application.instance_id:${server.port}:${spring.application.name}}:${spring.application.instance_id}
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    leaseRenewalIntervalInSeconds: 3
  client:
    region: default
    registryFetchIntervalSeconds: 5
#    serviceUrl:
#      defaultZone: ${vcap.services.discovery-service.credentials.uri:localhost:8761/eureka/
